### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by thiagorocha503** [thiagorocha503/to-do-app#1]
-   [x] User can see an `input` field where he can type in a to-do item
-   [x] By pressing enter (or a button), the User can submit the to-do item and can see that being added to a list of to-do's
-   [x] User can mark a to-do as `completed`
-   [x] User can remove a to-do item by pressing on a button (or on the to-do item itself)
